### ISSUE TITLE
Good timezone config, but 2 hours less on Observium

### ISSUE THREAD

**Issue by Draowyr** [somsakc/docker-observium#15]
Hello,

I have correctly configured the time zone with "Europe/Paris" for "mariadb" and "observium" but I still have a delay of two hours (less) compared to the real time.

How could I fix this? It totally distorts my graphics, it's impractical.

On the host server, the time is set with "Europe/Paris" too but I don't have this problem, the time is correct.

Regards,

Draowyr

**Comment by somsakc** [comment]
Hello,

I setup my small environment. I thought it worked properly in my  environment. Kindly see below.

$ docker-compose ps
     Name                    Command               State                  Ports                
-----------------------------------------------------------------------------------------------
observium_app_1   /usr/bin/supervisord -c /e ...   Up      0.0.0.0:8888->80/tcp,:::8888->80/tcp
observium_db_1    docker-entrypoint.sh mysqld      Up      3306/tcp      
                      
$ docker-compose exec db sh -c "echo \$TZ; date"
Europe/Paris
Mon Sep  6 16:41:23 CEST 2021

$ docker-compose exec app sh -c "echo \$TZ; date"
Europe/Paris
Mon 06 Sep 2021 04:41:31 PM CEST

$ date
Mon 06 Sep 2021 09:41:49 PM +07

My docker host is setup Asia/Bangkok (GMT+7).  Both containers are set to Europe/Paris. Their TZ and clock were Paris (GMT+2). I checked Paris localtime from Internet. It is likely the same time of both containers.

Note: I changed my TZ environment in docker-compose.yml file to Europe/Paris before down & up docker-compose. Here is my docker-compose file.
$ cat -n docker-compose.yml |grep TZ
    14	      - TZ=Europe/Paris
    31	      - TZ=Europe/Paris

Hopefully, it would be useful to you.

Regards,
Somsak C.
