### ISSUE TITLE
Requested URL probes does not exist

### ISSUE THREAD

**Issue by dunderrrrrr** [somsakc/docker-observium#16]
I have a clean docker installation of Observium. However it seems like the Probes-page is incorrect.

`http://observium.url/device/device=<device_id>/tab=edit/section=probes/  `
**Page does not exist**
_The requested page does not exist. Please correct the URL and try again._

I guess these packages are missing from the container, see https://docs.observium.org/probes/. How do I install these and make them permanent in the docker container? I guess you can docker exec -it, but it'll go away after a restart.

**Comment by somsakc** [comment]
You're right. It always go away after restart the container.
I need to rebuild the docker image again. It will be available soonest, thanks for your given information.

**Comment by somsakc** [comment]
I pushed newer docker image today.
