### ISSUE TITLE
Add support for custom database port

### ISSUE THREAD

**Issue by SimonWoidig** [somsakc/docker-observium#19]
Hello. Would it be possible to add functionality to set a custom database port?  
When I try to add it in the env OBSERVIUM_DB_HOST, it doesn't work, because you are using the `-h` flag only in the `observium-init.sh` script. The fix should be relatively easy, if this is the only place that needs fixing.  
Thanks!

**Comment by somsakc** [comment]
Yes, it is possible to custom it definitely. Is it possible to hint me more about which line or code to fix it. (due to I am still busy in my job. If you can help me, it will save time for me, thank in advance).
