### ISSUE TITLE
Running on a Synology NAS?

### ISSUE THREAD

**Issue by JayVDZ** [somsakc/docker-observium#2]
When I run the container in "bridge" mode on my Synology NAS, i.e. isolated, Observium works, though as it's an isolated environment it can't access any devices outside this isolated network, so useless. When I run it in host mode, i.e. not isolated, there's no port settings possible so I have no idea how to access the app.

Has anyone got it working on a Synology NAS?

**Comment by somsakc** [comment]
Hi Amethi,
Sorry, I did not have experience about Synology NAS product. Hope you find out resolution soonest.
P.S. Anyway, if I get any helpful source of information related to your case, I will share to you.

**Comment by JayVDZ** [comment]
Thanks anyhow.
