### ISSUE TITLE
Possible to send test E-Mail

### ISSUE THREAD

**Issue by Its-egner** [somsakc/docker-observium#20]
Hi,

is it possible to send Test E-Mail? is PHPMAiler working with this Image? Sendmail is not installed, i checked that.

Greetings

**Comment by Its-egner** [comment]
Found the Answer, in Observium Directory is a test_alert.php I checked that. But its only working with SMTP and no Authentication. Please Consider installiing sendmail in Future release od PHP Mailer

**Comment by somsakc** [comment]
I consider to install phpmailer package (libphp-phpmailer). I thought it should be fulfilled your need as well.

**Comment by somsakc** [comment]
I added libphp-phpmailer  in mbixtech/observium:22.5 image.
