### ISSUE TITLE
logrotate missing

### ISSUE THREAD

**Issue by Its-egner** [somsakc/docker-observium#21]
Hi,

the logrotate Package is missing i needed to install it manually to get it working.

root@065bbf5ecf55:/etc/logrotate.d# cat /opt/observium/logs/.logrotate.log.swp
/bin/sh: 1: /usr/sbin/logrotate: not found

Greetings

**Comment by somsakc** [comment]
Thank for that defect. I will research it in the container image (it is missing in image. I will fix it in new built soonest).

For workaround, yes you can fix it by quick mount that comment into container. Otherwise, you built your owned image from Dockerfile instead.

**Comment by somsakc** [comment]
I fixed it in mbixtech/observium:22.5 image.
