### ISSUE TITLE
Admin User Creation dont Work

### ISSUE THREAD

**Issue by Its-egner** [somsakc/docker-observium#23]
HI,

another Bug is that User creation not working, Ireviewed the Docker File its simply not implemented.

Grüße

**Comment by Its-egner** [comment]
It does not wirk with Special Charakters i Think

**Comment by somsakc** [comment]
I hope you solved it already.

Please be noted that user creation will be created automatically when you start the container image in first time (see observium-init.sh file) . 

You can review docker-compose.yml file as an idea. Both is customizable as you prefer.

  app:
    image: mbixtech/observium:22.5
    environment:
      - OBSERVIUM_ADMIN_USER=admin
      - OBSERVIUM_ADMIN_PASS=xxxxxx
 
Thanks
