### ISSUE TITLE
Error Docker not found

### ISSUE THREAD

**Issue by zibu9** [somsakc/docker-observium#25]
Hello.
i get this error 
/bin/sh: 1: docker: not found
when i execute

```
  $ docker run --name observiumdb \
    -v /home/docker/observium/data:/var/lib/mysql \
    -e MYSQL_ROOT_PASSWORD=passw0rd \
    -e MYSQL_USER=observium \
    -e MYSQL_PASSWORD=passw0rd \
    -e MYSQL_DATABASE=observium \
    -e TZ=Asia/Bangkok \
    mariadb 
```

what can i do ?

**Comment by somsakc** [comment]
Um, it looked that the docker command was not found.
I am not sure did you solve it or not? If not, ensure that you had installed docker package and set your PATH properly. Otherwise, could you follow https://docs.docker.com/engine/install/ first.
