### ISSUE TITLE
Feature request: OBSERVIUM_BASE_URL

### ISSUE THREAD

**Issue by dkrizic** [somsakc/docker-observium#3]
Hi,

could you please add a new environment variable that add this line to the config:

$config['base_url'] = "https://whatever"; # value of OBSERVIUM_BASE_URL

Otherwise I am not able to run behind a reverse proxy.

**Comment by somsakc** [comment]
Hi,

I added the feature of OBSERVIUM_BASE_URL already.
Thanks for valuable request.
