### ISSUE TITLE
Wrong Time Zone in Graphs

### ISSUE THREAD

**Issue by jiimint** [somsakc/docker-observium#32]
Hello
I have a problem with the time zone
I have set the variable TZ=Europe/Athens in both observiumdb: and observiumap: but my graphs show 3 hours behind. The observium itself has the correct time from the ip I log in to.
Is there any solution about it?

**Comment by somsakc** [comment]
I revised amd64/observium-init.sh file by updating /etc/timezone and /etc/localtime in container image whenever TZ environment is specified. It will effect to rrd graph.

Hopefully, it could fix your facing problem.
