### ISSUE TITLE
Please update to new version.

### ISSUE THREAD

**Issue by elizandropacheco** [somsakc/docker-observium#4]
This docker image is oltdated. Please upgrade to new version.

There is a newer revision of Observium available!
Version 18.9.1 (23rd August 2019) is 1292 revisions ahead.

**Comment by dkrizic** [comment]
I cloned the repository (https://github.com/dkrizic/docker-observium) and created a new Docker image that contains the new version (https://cloud.docker.com/u/dkrizic/repository/docker/dkrizic/observium).

**Comment by somsakc** [comment]
I added docker image with new Observium CE version 19.8.10000 for both amd64 and arm32v7 platforms. Enhanced some configuration and scripts, see changelogs.
