### ISSUE TITLE
Install using docker-compose and DB errors. 

### ISSUE THREAD

**Issue by robertcdonovan** [somsakc/docker-observium#7]
observiumap_1_d750d79a9f9c | [3] Verifying coonection to observium database.
observiumap_1_d750d79a9f9c | mysql: [Warning] Using a password on the command line interface can be insecure.
observiumap_1_d750d79a9f9c | ERROR 2003 (HY000): Can't connect to MySQL server on 'observiumdb' (111)
observiumap_1_d750d79a9f9c | [4] Verifying coonection to observium database.
observiumap_1_d750d79a9f9c | mysql: [Warning] Using a password on the command line interface can be insecure.
observiumap_1_d750d79a9f9c | ERROR 2003 (HY000): Can't connect to MySQL server on 'observiumdb' (111)
observiumap_1_d750d79a9f9c | [5] Verifying coonection to observium database.
observiumap_1_d750d79a9f9c | mysql: [Warning] Using a password on the command line interface can be insecure.
observiumap_1_d750d79a9f9c | ERROR 2003 (HY000): Can't connect to MySQL server on 'observiumdb' (111)

When I connect to the web portal
DB Error 2006: MySQL server has gone away

here is the edited docker compose
version: '3'

services:
  observiumdb:
       image: mariadb:latest
       environment:
         - MYSQL_ROOT_PASSWORD=xxxxxxxxxx
         - MYSQL_USER=observium
         - MYSQL_PASSWORD=xxxxxxxxxxx
         - MYSQL_DATABASE=observium
         - TZ=America/New_York
       volumes:
         - ./data:/var/lib/mysql
       networks:
         - back-tier
       restart: always

observiumap:
       image: mbixtech/observium
       environment:
         - OBSERVIUM_ADMIN_USER=admin
         - OBSERVIUM_ADMIN_PASS=xxxxxxxxxxxxxxx
         - OBSERVIUM_DB_HOST=observiumdb
         - OBSERVIUM_DB_NAME=observium
         - OBSERVIUM_DB_USER=observium
         - OBSERVIUM_DB_PASS=xxxxxxxxxxxxxxxxx
         - OBSERVIUM_BASE_URL=http://observium.mbixtech.com:8888
         - TZ=America/New_York
       volumes:
         - ./logs:/opt/observium/logs
         - ./rrd:/opt/observium/rrd
       networks:
- back-tier
       ports:
         - "8888:80"
       restart: always
       depends_on:
         - observiumdb

networks:
  back-tier:
      driver: bridge

**Comment by somsakc** [comment]
The output seem cut for some period shortly. I guess about MySQL was still initializing. Could you take a lot about MySQL first. For first MySQL startup, it take more time to create a new database.
